# Generated by Django 6.0 on 2025-12-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Social Links'},
        ),
    ]
